#build frontend in npm

FROM node:16-alpine as builder

RUN apk add --update git
ARG ACC_FE
RUN git clone https://github.com/LAYAIraq/LAYA-Iraq-Frontend.git
WORKDIR /LAYA-Iraq-Frontend
RUN npm install
RUN npm run build

# Build has to be done in NPM Project
FROM nginx:stable-alpine as production

# Copy production-ready build into Docker
COPY --from=builder /LAYA-Iraq-Frontend/dist /usr/share/nginx/html

# Expose the build at Port 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
