version: "3.7"

services:
  laya-frontend:
    image: laya-frontend:latest
#    image: gitlab.informatik.hu-berlin.de:4567/laya/vechta/laya-vechta-backend/master:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        ACC_FE: $ACC_FRONTEND
        VUE_APP_BACKEND_HOST: ${PROXY_DOMAIN}
        VUE_APP_BACKEND_PORT: ${API_PORT}
        VUE_APP_BACKEND_ROOT: ${API_ROOT}
    container_name: laya-frontend
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - laya-frontend-files:/usr/share/nginx/html
#    links:
#      - laya-backend
  laya-backend:
#    image: gitlab.informatik.hu-berlin.de:4567/laya/vechta/laya-vechta-backend/master:latest
    image: laya-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        ACC_BE: $ACC_BACKEND
        API_PORT: $API_PORT
        DB_PATH: $DB_PATH
        DB_NAME: $DB_NAME
        FILES_PATH: $FILES_PATH
    container_name: laya-backend
    restart: always
    ports:
      - "${API_PORT}"
    env_file: .env
    environment:
      - NODE_ENV=$ENVIRONMENT
      - ADMIN_MAIL=$ADMIN_MAIL
      - API_ROOT=$API_ROOT
      - API_PORT=$API_PORT
      - DB_PATH=$DB_PATH
      - DB_NAME=$DB_NAME
      - FILES_PATH=$FILES_PATH
      - FILES_MAX_SIZE=$FILES_MAX_SIZE
      - FRONTEND_HOST=$PROXY_DOMAIN
      - FRONTEND_PORT=443
      - MAIL_AUTH_PASS=$MAIL_AUTH_PASS
      - MAIL_AUTH_USER=$MAIL_AUTH_USER
      - MAIL_FROM=$MAIL_FROM
      - MAIL_HOST=$MAIL_HOST
      - MAIL_PORT=$MAIL_PORT
    volumes:
      - laya-db:/laya-backend/${DB_PATH}
      - laya-backend-files:/laya-backend/${FILES_PATH}
  reverse-proxy:
    image: cmaufc/ssl-reverse-proxy:v0.2-release
    restart: unless-stopped
    container_name: ssl-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TARGET_HOST=laya-frontend
      - TARGET_PORT=80
      - SERVER_NAME=${PROXY_DOMAIN}
      - SSL_PORT=443
      - API_ROOT=${API_ROOT}
      - API_HOST=laya-backend
      - API_PORT=${API_PORT}
    volumes:
      - ./cert:/etc/nginx/certs
      - laya-proxy-logs:/var/log/nginx
    links:
      - laya-frontend
      - laya-backend

volumes:
  laya-backend-files:
  laya-db:
  laya-frontend-files:
  laya-proxy-logs:
