version: "3.7"

services:
  laya-frontend:
    image: laya-frontend:latest
    ports:
      - "8000:80"
  laya-backend:
    image: laya-backend:latest
    ports:
      - "3001:3001"
    volumes:
      - laya-db:/var/www/laya/backend
      - laya-files:/var/www/laya/backend/server/files
  reverse-proxy:
    image: fsouza/docker-ssl-proxy
    environment: 
      - DOMAIN=laya.uni-vechta.de
      - TARGET_PORT=8000
      - TARGET_HOST=laya-frontend
      - SSL_PORT=443
    volumes:
      - ./cert:/etc/nginx/certs

volumes:
  laya-db:
  laya-files:
      