version: "3.9"

services:
  laya-frontend:
    image: laya-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: laya-frontend
    restart: always
    ports:
      - "80"
    environment:
      - VUE_APP_BACKEND_PORT=3001
      - VUE_APP_MAX_FILE_SIZE=$FILES_MAX_SIZE
  laya-backend:
    image: laya-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: laya-backend
    restart: unless-stopped
    ports:
      - "3001"
    env_file: .env
    environment:
      - NODE_ENV=$ENVIRONMENT
      - SUPERADMIN_MAIL=$SUPERADMIN_MAIL
      - API_ROOT=$API_ROOT
      - API_PORT=$API_PORT
      - DB_PATH=$DB_PATH
      - DB_NAME=$DB_NAME
      - FILES_PATH=$FILES_PATH
      - FILES_MAX_SIZE=$FILES_MAX_SIZE
      - FRONTEND_HOST=$PROXY_DOMAIN
      - FRONTEND_PORT=443
      - MAIL_AUTH_PASS=$MAIL_AUTH_PASS
      - MAIL_AUTH_USER=$MAIL_AUTH_USER
      - MAIL_FROM=$MAIL_FROM
      - MAIL_HOST=$MAIL_HOST
      - MAIL_PORT=$MAIL_PORT
      - MAIL_CONNECTOR=$MAIL_CONNECTOR
    volumes:
      - laya-db:/LAYA-Iraq-Backend/${DB_PATH}
      - laya-backend-files:/LAYA-Iraq-Backend/${FILES_PATH}
  reverse-proxy:
    image: laya-reverse-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile.proxy
    restart: unless-stopped
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TARGET_HOST=laya-frontend
      - TARGET_PORT=80
      - SERVER_NAME=${PROXY_DOMAIN}
      - SSL_PORT=443
      - API_ROOT=${API_ROOT}
      - API_HOST=laya-backend
      - API_PORT=${API_PORT}
    volumes:
      - proxy-logs:/var/log/nginx
    links:
      - laya-frontend
      - laya-backend

volumes:
  laya-backend-files:
  laya-db:
  proxy-logs:
